### ISSUE TITLE
Pushing to refs/publish/master/my/local/branch instead of refs/publish/master

### ISSUE THREAD

**Issue by benma** [emacsorphanage/magit-gerrit#24]
Hi

When pushing any commit for review, the local branch name is appended to the ref. This results in gerrit adding a topic which is the name of my local branch.

This should be configurable, as in my workflow, we are not using topics like that. The option should be one of three things:
- Default to local branch name as topic (make that the default for backwards compat. if needed).
- Default to no topic
- Default to querying the user for the topic

Even cooler if choosing the option could somehow be baked into the magit popup.

**Comment by terranpro** [comment]
Hello!  This is a good idea.  Most people I work with also don't use topics in this manner.
Customizing this should be done and baking it into the magit popup is definitely a possibility.

Let me try a couple of things for this.  One potential downside is it could require an extra keystroke and for the push commit for review to become a submenu instead of a one-shot deal.  But this might actually make more sense since push might not be a one-size fits all.

We might even consider having the remote branch auto-selected/guessed but changeable in the submenu popup along with the topic - which might also be an improvement w/regard to issue #22 

Will keep thinking on it; feel free to share any more thoughts/ideas!

Brian

**Comment by terranpro** [comment]
Hi @benma 

I've been experimenting with your idea and I've discovered it's actually possible to build/modify magit popups on the fly.

Buffer local variable `magit-gerrit-use-topics' :
  - controls the default for topics being on/off and defaults to off.  
  - if you need to change, just  hit `=t`

The menus are now context sensitive too based on cursor position:
  over reviews => verify, code review, submit, abandon

  over commits => push review, push draft, topics/remote branch options

This is only in `next` branch for now - hoping to get some feedback and make sure this is actually an improvement!

**Comment by tarsius** [comment]
This package isn't being maintained anymore and so no new features are added.
