### ISSUE TITLE
magit-gerrit-section: Symbol's function definition is void: section

### ISSUE THREAD

**Issue by jdees** [emacsorphanage/magit-gerrit#46]
When I type any command with magit-gerrit I get the error 
Symbol's function definition is void: section

looking at the source code, e.g.: (magit-insert-section (section approval))

I see that you use the function "section" - apparently it is not defined?
What do do to fix this?

Btw here my used versions:
magit              20160525.1745 installed             A Git porcelain inside Emacs
magit-gerrit       20160226.130  installed             Magit plugin for Gerrit Code Review
magit-popup        20160521.1221 installed             Define prefix-infix-suffix command combos

**Comment by jdees** [comment]
some update: I updated another issue in magit as I am not sure whose "fault" it is:
https://github.com/magit/magit/issues/2663

Also found out that the bug comes from:
(require 'magit)
(require 'magit-popup)
(require 'magit-gerrit)

uncommenting (require 'magit-popup) makes it work again.
Fell free to investigate further or just close the bug/follow up on magit page.

**Comment by tarsius** [comment]
@terranpro You don't have to avoid attempting to require `magit-popup` in case it isn't available because it is part of all magit versions which you support (`Package-Requires: ((magit "2.3.1"))`). By the way, a better way to load a feature, but only if it is available, would be `(require 'magit-popup nil t)`. Furthermore you don't actually have to load `magit-popup` because loading `magit` already does that.

> looking at the source code, e.g.: (magit-insert-section (section approval))
> I see that you use the function "section" - apparently it is not defined?

`section` isn't a function in this context; it is the type of the section being inserted by this `magit-insert-section`. It is a symbol and does not have to be quoted, so this is correct.

@terranpro It's correct in a technical sense, but you shouldn't use `section` as a section type. You should different section types for different... uhm types of sections, e.g. `gerrit-commit`, `gerrit-issues`, and `gerrit-issue`.

> When I type any command with magit-gerrit I get the error 
> Symbol's function definition is void: section

But I don't think that's the issue here. @jdees Please remove all of magit's and magit-gerrit's `*.elc` files, restart Emacs, type `M-x debug-on-error RET` and then "type any command". This shows a backtrace in a separate buffer. Post that here.

Please put three backticks before and after the posted output, on separate lines. That makes the output more readable. See the "Styling with Markdown is supported" link below for more information.

**Comment by tarsius** [comment]
@jdees Is `dash` installed an available on the `load-path`?

**Comment by tarsius** [comment]
By now this doesn't use `magit-popup` anymore.
