### ISSUE TITLE
remove from MELPA

### ISSUE THREAD

**Issue by ghost** [emacsorphanage/magit-gerrit#59]
Seems like this package has been abandoned. Would it possible to remove it from MELPA and replace it with https://github.com/pangwa/magit-gerrit2 to avoid confusion for new users?

**Comment by aspiers** [comment]
https://github.com/pangwa/magit-gerrit2 is not currently a good choice of successor, because it doesn't have the issue tracker enabled.  It also has at least two problems, probably due to a blanket `s/magit-gerrit/magit-gerrit2/g' search and replace:

- https://github.com/pangwa/magit-gerrit2/commit/ea576a70e2e42bdad5c14291d823ce6759c5a8e9#commitcomment-32890575
- The README.md incorrectly claims "If you have a recent Emacs with package.el, you can install magit-gerrit2 from MELPA", but `magit-gerrit2` does not exist on MELPA.

I would gently suggest that any fork which aims to take over from an unmaintained project needs to make sure that it has got all the details correct before taking over.

I see a noble attempt from @somtin to [repoint MELPA at his fork](https://github.com/melpa/melpa/commit/f6bd0952a5150768acda175474c10a73e144e9d1) but unfortunately it hasn't worked yet since at the time of writing [MELPA's `magit-gerrit`](https://melpa.org/#/magit-gerrit) still points to this original version from @terranpro.

So currently we have two failed forks, and MELPA still pointing to the old broken version.  Hopefully we can tidy this up somehow in the short-term.  Long term, I think the better approach is to [add Gerrit support to Forge](https://github.com/magit/forge/issues/60).

/cc @tarsius

**Comment by aspiers** [comment]
[Just heard](https://github.com/magit/forge/issues/60#issuecomment-492269877) that there's also https://github.com/darcylee/magit-gerrit which doesn't have any of these issues.

**Comment by tarsius** [comment]
If both @terranpro and @darcylee agree to transfer maintainership, then Melpa could be updated.

**Comment by darcylee** [comment]
I am very willing to be the maintainer of magit-gerrit. But I am a newcomer to elisp, I want to try it out and keep learning.

**Comment by aspiers** [comment]
@darcylee It looks like you are active on your fork, but you don't have the issue tracker enabled, therefore unfortunately currently it is unusable as an Open Source project because there is no way to report bugs or request features.  If you are still willing to be the maintainer that would be awesome, but please could you enable the issue tracker?

**Comment by tarsius** [comment]
It would be best if @terranpro would transfer this repository to a group of maintainers. This could be done simply by giving those users the necessary rights, but I think it would be better to also transfer the repository itself somewhere else.

As the maintainer of the [Emacsmirror](https://emacsmirror.net) and due to my involvement with Melpa, I deal with this sort of thing a lot lately. The [Emacsorphanage](https://github.com/emacsorphanage) was created for that purpose.

To roadmap is something like this:

1. @terranpro agrees to do this and states whether they want o stay involved at all.
2. I invite @terranpro to the `emacsorphanage` organisation to allow him to transfer.
3. @terranpro performs the transfer.
4. Depending on whether @terranpro wants to stay involved I either revoke their membership or give them near extended access to the tranferred repository.
5. I give other users access.
6. Those users do the maintaining but I can be summoned for admin work (such as adding more new maintainers) or in case of problems.

**Comment by aspiers** [comment]
Thanks a lot for the advice @tarsius!  That all sounds good to me.

I just checked the various forks here, and @darcylee's seems to be much more recent than the others so based on that and [this comment](https://github.com/terranpro/magit-gerrit/issues/59#issuecomment-492738329) they seem like the obvious candidate to be the next maintainer.

**Comment by tarsius** [comment]
> I am very willing to be the maintainer of magit-gerrit. But I am a newcomer to elisp, I want to try it out and keep learning.

(Sorry for not responding to that earlier!)

Great!

@aspiers are you willing to lend him a hand?

Seems the next step is to contact @terranpro by email.

**Comment by aspiers** [comment]
[**@tarsius**](https://github.com/tarsius) commented on [November 5, 2019 11:33 AM](https://github.com/terranpro/magit-gerrit/issues/59#issuecomment-549785276 "2019-11-05T11:33:52Z - Replied by Github Reply Comments"):
> [@aspiers](https://github.com/aspiers) are you willing to lend him a hand?

I'm willing to answer questions and try to fix bugs I discover myself, but my time will be very limited for the next 6 months at least.

**Comment by thisch** [comment]
FYI I have developed a similar package called [gerrit.el](https://github.com/thisch/gerrit.el). This package will hopefully [soon](https://github.com/melpa/melpa/pull/6592) be available on MELPA.

The diff between `gerrit.el` and `magit-gerrit` is that the former uses the `git-review` for uploading/downloading gerrit changes, while the latter uses [push-options](https://gerrit-review.googlesource.com/Documentation/user-upload.html). Since `git-review` currently does not allow to set the assignee of a gerrit change, `gerrit.el` will (probably in Jannuary) use gerrits REST interface for that.

**Comment by terranpro** [comment]
Hi all, sorry I haven't responded sooner, I apparently silenced github notifications long ago and haven't been getting email updates.  I would be glad to step aside and let another(s) take over maintenance.  Unfortunately, my workplace stopped using Gerrit almost 2 years ago and I haven't had the motivation or the test servers to continue development on magit-gerrit.

Not sure if those who forked the repo saw the next branch, but I had made some changes there that I thought were worthy improvements, but never got around to merging to master.  I'm sure they've also put significant work into their forks.

@tarsius I would be glad to work thru the process you described to make the transfer, but would appreciate if I could remain involved in some capacity in case I get the chance to work with gerrit again in the future (I really miss those days!)

**Comment by tarsius** [comment]
@terranpro I missed your reply before.

How do you want to go about this? Would you like to transfer the repository to the `emacsorphanage` and I then take care of assigning other maintainers. The easiest way to do that is for you to transfer the repository to my user account (`tarsius`) and I then transfer to the `emacsorphanage`. I'll keep your permissions intact.

**Comment by dakra** [comment]
I just saw in [this reddit thread](https://www.reddit.com/r/emacs/comments/gjotu6/best_magitgerrit_fork/)
that apparently there is another fork with quite a few additions
since this issue was raised over a year ago.

Maybe @xmagpie (?) and @darcylee can combine efforts?

**Comment by tarsius** [comment]
The most promising forks appear to be
- https://github.com/ispras/magit-gerrit
- https://github.com/dakra/magit-gerrit

**Comment by tarsius** [comment]
Even if future work were based on one of these forks it would still be nice not to loose the issues from the original upstream repository. @terranpro you could have to transfer the repository to me so that I could take care of organizing that as I suggested above (https://github.com/terranpro/magit-gerrit/issues/59#issuecomment-601281318).

**Comment by xmagpie** [comment]
Hello everyone!

I was mentioned in this thread by @dakra. Yes, me and a couple of my mates (@ge0pan) have [forked](https://github.com/ispras/magit-gerrit) this repo sometime ago. We have tweaked it a little bit and have tried to add some experimental functionality. Unfortunately, we have not got much time to work on it and improve it lately.

I am eager to collaborate. I believe if someone finally makes a transfer we can review our current changes and upload them as pull-requests. Moreover, I can take part in discussions and try reviewing the code (though I am not very strong with elisp nowdays) in the future. However, as I said, I am not sure I will have much time to actually write code or implement new features. 

Apparently, the issues tab in our fork was closed. I have opened it in case anyone will need to leave issues.

**Comment by tarsius** [comment]
Inviting @ispras to the conversation. :wave:

**Comment by xmagpie** [comment]
@tarsius, sorry, but please do not mention the whole ispras organization here. There are many people out there, but for now, only I (@xmagpie) and @ge0pan know something about this repository. I think it is better to directly contact us, if necessary

**Comment by tarsius** [comment]
Oh... I didn't realize that was an organization. Sorry about that.

**Comment by tarsius** [comment]
I suggest we do this:

1. @terranpro transfers the repository to me.
2. I transfer the repository to the emacsorphanage. (Directly is not possible because Github does not allow non-members to transfer to an organization.)
3. I invite @xmagpie and @ge0pan
4. The accept and push their version.
5. I do a brief review.
6. I update the recipe.

**Comment by xmagpie** [comment]
Seems good to me. Sorry for slow replies, lots of work :)

**Comment by thisch** [comment]
FYI My gerrit.el MELPA pkg now has support for gerrit - see the screenshots on the github page https://github.com/thisch/gerrit.el

I would love to add support for commenting on gerrit changes, but for this I need support from the community.

**Comment by tarsius** [comment]
That looks nice!

**Comment by vedang** [comment]
Hello, I recently started using Forge, and I realized how cool it was to interact with Github directly through Magit. I'd love to have something that cool to play around with Gerrit as well. Following the trail brought me here, I wanted to check in to see if this issue / plan has seen any traction since last Jul.

**Comment by tarsius** [comment]
It seems someone has to contact @terranpro by mail again and point them to the six steps above (https://github.com/terranpro/magit-gerrit/issues/59#issuecomment-634253916), in particular the first one.

**Comment by terranpro** [comment]
Hi @tarsius , I just requested transferred membership of the repo to you.  
Thanks for handling the heavy lifting, and apologies for the slow response!

Long Live Magit Gerrit!

**Comment by tarsius** [comment]
Thanks!

**Comment by vedang** [comment]
@xmagpie @ge0pan : Please push your changes to `magit-gerrit`, looking forward to trying them out from this official package :)

**Comment by tarsius** [comment]
Here's a link for quick access: https://github.com/emacsorphanage/magit-gerrit.

There's a bunch of pull-requests and I will try to look at those eventually, but if you would like me to prioritize something, then please refresh it a bit and then ping me.

**Comment by ge0pan** [comment]
@vedang We'll try to review our code in near future. I guess we might need to refresh our README and so on.
Also, I want to point out that in our version we started migration to the gerrit REST API. So, half of the functionality relies on the old (`ssh`) api, another half on the new api. And the plugin requires you to specify your gerrit REST address to work.
What do you think of this approach, is it critical for now that it works both via `ssh` and REST requests? We planned on migrating fully to the new api because for our case it works alright (we manage our gerrit instance ourself).
