### ISSUE TITLE
Push for review seems to be incompatible with Gerrit 3.2.3

### ISSUE THREAD

**Issue by andy-sheen** [emacsorphanage/magit-gerrit#64]
Hi

Using the MELPA version from April and trying to push for review using R->P

Two issues here. Firstly, we use refs/for to push to and refs/publish is not a pushable branch in our setup. This is simply rectified by redefining `magit-gerrit-create-review` as 

```
(defun magit-gerrit-create-review ()
  (interactive)
  (magit-gerrit-push-review 'for))
```

however, that tries to push to `refs/for/master/<branchname>` (when selecting the master branch as the target). This fails with `branch master/<branchname> not found`

This gerrit instance uses this format of push:

` git push origin HEAD:refs/for/master%topic=<branchname>`

Changing the string `"refs/%s%s/%s"` at line 413 to `"refs/%s%s%%topic=%s"` allows the R->P to work. Other than redefining the function in `init.el` (I won't edit `magit-gerrit.el`), is there any other workaround?

Thanks

Andy

**Comment by andy-sheen** [comment]
PS. Thanks for taking on this really REALLY useful addon.

**Comment by tarsius** [comment]
> (I won't edit `magit-gerrit.el`)

Why not? Could you open a pull-request that adds an option or git variable to make this string customizable?

**Comment by andy-sheen** [comment]
Yikes. I've used emacs for 30 years and have never actually written a line of code for it.... I'll give it a go as it seems fairly simple to define a variable...

**Comment by tarsius** [comment]
Well well. Better late than never.

;P

**Comment by andy-sheen** [comment]
So.. I have created a change that works for me (at least, I think it does!). Only issue is that I have my editor set to turn tabs into 8 spaces so has quite a bit of churn. Do you want me to create a pull request for this or you want me to redo the commit with tabs in?

**Comment by tarsius** [comment]
Please open a pull-request. I can cleanup the whitespace.

**Comment by andy-sheen** [comment]
As an aside, we use spaces here to avoid different visuals when people have tabs set differently. Given it is only a single file, it might be better to adopt spaces rather than tabs...

**Comment by tarsius** [comment]
> As an aside, we use spaces here to avoid different visuals when people have tabs set differently. Given it is only a single file, it might be better to adopt spaces rather than tabs...

1. Such a change should be made in a separate commit.
2. Let's not do it at all.

If you have configured your Emacs so that your tab-width-preference for C (or whatever) affects emacs-lisp, then you have done it wrong. You should only set the `tab-width' for specific modes.

I have added a separate commit that enforces the use of `indent-tabs-mode`. I rebased your commit on top of that and did cleanup whitespace and wording. Something might have gone wrong in the process, please verify that the real changes are still present as intended after my edits.

**Comment by andy-sheen** [comment]
`indent-tabs-mode` is set to `nil` here, except for `makefile-mode-hook`. I know use of tabs/spaces is a divisive one. New changes look right though. Real changes are still there after your changes.

**Comment by andy-sheen** [comment]
PS. The tabs/spaces problem only becomes an issue when collaborating with more than a handful of people and people use wildly  different editors.

**Comment by tarsius** [comment]
Personally I prefer spaces but don't want to change the intention style used in an existing file by someone else. Emacs lisp is usually edited using Emacs and other editors can be ignored in this case. I recommend setting `indent-tabs-mode` for every project explicitly because otherwise there will always be people who have set the other value.
